### ISSUE TITLE
Disconnected wallet view does not load Avalance vault deposits/max cap

### ISSUE THREAD

**Issue by kargakis** [ribbon-finance/ribbon-frontend#312]
Avalance vault deposits and max capacity will only show up when the wallet is connected and the network is switched to Avalance. It would be nice to still show deposits and max capacity in the initial view to stay consistent with the rest of the vaults.
![screen](https://user-images.githubusercontent.com/3900799/146657829-32bfffe7-cb8d-4ed6-83e4-f89dc09c9f76.png)

**Comment by fqlx** [comment]
Thank you and we plan on fixing this. Currently, it's only loading a single provider of what network Metamask is connected to. For the fix, we need to load multiple web3 providers (one for the ETH and one for the AVAX RPC).

**Comment by kargakis** [comment]
Fixed by https://github.com/ribbon-finance/ribbon-frontend/pull/315
