### ISSUE TITLE
Modal blurred background

### ISSUE THREAD

**Issue by janklimo** [ribbon-finance/ribbon-frontend#313]
Hey team, huge fan of Ribbon's UX 💯 warms my heart to see folks obsess over details.

I noticed the modal backdrop blur does a bit of a stutter when transitioning, as seen [here](https://recordit.co/oz5wg8pxWx).

Had a similar problem when I was working on our (Pickle) app redesign but I managed to find an approach that is smooth. It's a WIP but you can see it [here](https://app.pickle.finance/v2) when you click on Harvest rewards. It's using Tailwind but I'm sure you can borrow the right elements and CSS rules.

Happy building!

**Comment by kenchangh** [comment]
Hey @janklimo thanks for the shout. Would you mind pointing us to the Pickle JS code that handles the background blur, and how yall have circumvented the issue?

**Comment by janklimo** [comment]
It probably doesn't transfer well to your codebase since it's Headless UI + Tailwind but worth a shot ([source](https://github.com/pickle-finance/pickle-ui/blob/master/v2/components/HarvestModal.tsx)).

**Comment by cjinghong** [comment]
That is weird. Been trying to reproduce on Chrome, Safari and Firefox and unable to seems to do so. [Here](https://vimeo.com/658871834) is my attempt or reproduction, may I know more about the environment you are running? 

OS: 
Browser: 
Browser Version:

**Comment by janklimo** [comment]
Hm it's possible it's a macOS thing, feel free to close. I'm sure you guys have bigger fish to fry 😅 

OS: macOS Big Sur 11.6.1
Browser: Chrome 96.0.4664.110

**Comment by cjinghong** [comment]
No worries, it appeared that this issue happens only in Mac's Chrome, able to recreate on my Mac as well. Was using a non-mac laptop because my Mac is laggy.
